export const VITE_PLUGIN_CRX_MV3 = 'vite-plugin-crx-mv3'
export const UPDATE_CONTENT = 'UPDATE_CONTENT'
// export const UPDATE_SERVICE_WORK = 'UPDATE_SERVICE_WORK'
export const RELOAD = 'RELOAD'
export const CONTENT_SCRIPT_DEV_PATH = 'content-scripts/content-dev.js'
export const SERVICE_WORK_DEV_PATH = 'background-dev.js'
